# Generated by Django 3.0.3 on 2020-05-16 01:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200516_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blog_content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='blog_title',
            field=models.CharField(max_length=200),
        ),
    ]
