# Generated by Django 3.0.3 on 2020-05-17 04:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200516_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blog_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
