# Generated by Django 3.0.3 on 2020-06-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_blog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blog_photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='assets/%Y/%m/%d/'),
        ),
    ]
