# Generated by Django 3.0.3 on 2020-06-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200602_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blog_photo',
            field=models.ImageField(default='./media/assets/default.jpg', upload_to='assets/%Y/%m/%d/'),
        ),
    ]
