# Generated by Django 3.0.3 on 2020-05-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='oghenerhona-ideh'),
        ),
    ]
