# Generated by Django 3.0.3 on 2020-05-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='value_1',
            field=models.CharField(default='Journalist', max_length=50),
        ),
        migrations.AddField(
            model_name='author',
            name='value_2',
            field=models.CharField(default='Beautiful', max_length=50),
        ),
    ]
