# Generated by Django 3.0.3 on 2020-06-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20200512_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='snap',
            field=models.ImageField(blank=True, upload_to='data/%Y/%m/%d/'),
        ),
    ]
